site_name: mkShapesRDF
nav:
    - Home: index.md
    - 'Framework':
      # - 'mkShapesRDF': 'mkShapesRDF.md'
      - 'Runner': 'runner.md'
      - 'Configuration Folder Structure': 'config.md'
theme: 
  name: readthedocs

plugins:
- search:
    indexing: 'full'
- mkdocstrings:
    custom_templates: templates
    default_handler: python
    handlers:
      python:
        options:
          show_root_heading: true
          show_source: false